### ISSUE TITLE
isdirty

### ISSUE THREAD

**Issue by fmuqtadi** [mchrbn/unity-traffic-simulation#12]
unity editor giving me these error , any idea?
Assets\unitysimulation\Assets\TrafficSimulation\Scripts\Editor\TrafficEditor.cs(292,32): error CS0117: 'EditorUtility' does not contain a definition for 'IsDirty'

Failed to load 'C://testing/test/Assets/unitysimulation/Assets/TrafficSimulation/Examples/Scenes/Example_01/LightingData.asset' because it was serialized with a newer version of Unity. (Has a higher SerializedFile version)
UnityEditorInternal.InternalEditorUtility:ProjectWindowDrag(HierarchyProperty, Boolean)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)

**Comment by MSchmoecker** [comment]
Hi, it seems as you using an older of Unity where the function EditorUtility.IsDirty() doesn't exists. 
Luckily this call isn't necessary at all, so it can be removed without breaking something

**Comment by fmuqtadi** [comment]
> Hi, it seems as you using an older of Unity where the function EditorUtility.IsDirty() doesn't exists.
> Luckily this call isn't necessary at all, so it can be removed without breaking something

I am trying to use a traffic simulation GitHub project in my unity project, it is giving me a lot of error
i don't have programming skills that why I want to use prefab,
