### ISSUE TITLE
Recommendation for performance boost

### ISSUE THREAD

**Issue by tetreum** [mchrbn/unity-traffic-simulation#13]
Hi!
Some months ago i did [peque-traffic](https://github.com/tetreum/peque-traffic) . I'm 100% sure you won't like the way it's coded & etc, so don't look at it. I wanted to share with you a heavy improvement that i applied to it recently (i didn't push it to the repo yet).

On runtime, all waypoints are converted to basic data classes and all scene waypoints are deleted to avoid having their Monobehaviours. Doing that i got a gain of over 27fps.

On my tests (with my package in Editor mode on Unity 2019.3.7f1):
Having 55 vehicles & over 220 waypoints made the scene drop to 45FPS. Removing the vehicles did nothing, while deleting all waypoints increased them to 72FPS.

Frames were measured with:
```c#
using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using UnityEngine.UI;

[RequireComponent(typeof(Text))]
public class FPSCounter : MonoBehaviour
{
    const float fpsMeasurePeriod = 0.5f;
    private int m_FpsAccumulator = 0;
    private float m_FpsNextPeriod = 0;
    private int m_CurrentFps;
    const string display = "{0} FPS";
    private Text m_Text;


    private void Start() {
        m_FpsNextPeriod = Time.realtimeSinceStartup + fpsMeasurePeriod;
        m_Text = GetComponent<Text>();
    }


    private void Update() {
        // measure average frames per second
        m_FpsAccumulator++;
        if (Time.realtimeSinceStartup > m_FpsNextPeriod) {
            m_CurrentFps = (int)(m_FpsAccumulator / fpsMeasurePeriod);
            m_FpsAccumulator = 0;
            m_FpsNextPeriod += fpsMeasurePeriod;
            m_Text.text = string.Format(display, m_CurrentFps);
        }
    }
}
```

Hope it helps!

**Comment by mchrbn** [comment]
hey @tetreum sorry for the late answer and thanks a lot for your suggestion, I will check it out!
