### ISSUE TITLE
Cars crashing into each other at intersections

### ISSUE THREAD

**Issue by EllaMaxine** [mchrbn/unity-traffic-simulation#14]
I have no idea why it's happening, but the cars are constantly crashing into each other. I just opened the example scene and it's not working. Maybe someone knows why this is happening...

![Desktop 2020 09 02 - 17 40 02 01_Moment(2)](https://user-images.githubusercontent.com/70652626/92005714-17bc5900-ed44-11ea-862f-75715bf7df78.jpg)
![Desktop 2020 09 02 - 17 40 02 01_Moment(3)](https://user-images.githubusercontent.com/70652626/92005719-18ed8600-ed44-11ea-9cd4-be16af1269ef.jpg)
![Desktop 2020 09 02 - 17 40 02 01_Moment](https://user-images.githubusercontent.com/70652626/92005721-19861c80-ed44-11ea-815b-2703bfa28fea.jpg)

**Comment by mchrbn** [comment]
Do you have any error messages? Not sure if it changes anything but it seems you target platform is Android, does it work if you switch it to Windows?

**Comment by EllaMaxine** [comment]
I get absolutely nothing, no warnings or errors. I will attempt to change the target platform as soon as I get home. I will let you know if something changes :)

**Comment by EllaMaxine** [comment]
Alright, I switched to PC Standalone and they're still crashing. Also no error messages :(

**Comment by mchrbn** [comment]
Ahh it's because your cars layer is set to "Roads" and not to "AutonomousVehicle". Each cars (+all their children) need to have the tag and layer set to "AutonomousVehicle"

**Comment by EllaMaxine** [comment]
I created a new layer called "AutonomousVehicle" and set all the cars to it. Now it's working perfectly, thank you :D
