### ISSUE TITLE
Set Passive - Active problem

### ISSUE THREAD

**Issue by menez1111** [mchrbn/unity-traffic-simulation#17]
Hello. I am making a mobile game and I am using your system (thank you for the system ) I have a lot of cars in the scene currently (40 -50) and I have 3 traffic system. It was really laggy because of the AI car and vehicle psychics so I decided to make them passive and active whenever my car enter the their area ( box collider) it almost worked well expect a big bug. As I understand when I make the AI Cars passive and when I come back to the same point cars that in the intersection area ( probably cars that have to stop bool) just stuck and never move again. In video I tried to capture I hope you can see it. I can share my project with you if you want to see what is the problem. Also, I want to share my project with you to show about I could not able to add new cars with AI system. 

video of the bug you can see the car which I zoomed totally stucked
https://youtu.be/EqACDfeV7SU 
That is my performance code
 

[ss.txt](https://github.com/mchrbn/unity-traffic-simulation/files/5221728/ss.txt)
![image](https://user-images.githubusercontent.com/53665690/93150917-0fc8c580-f703-11ea-87cb-a23c95c4e258.png)

**Comment by mchrbn** [comment]
I tried to set a car (the whole gameobject, not just the CarAI script) to active/inactive and I don't have any issue, however setting the traffic system to  active/inactive is messing up things so it shouldn't be done.

You should use only one traffic system, I never tried with more than one. And then if you activate/deactivate cars depending on which zone (box colliders) your main car enters, it should work.

That said, this system is still in early stages so maybe not suitable to develop a game :). I will work on improving performance in the following months (as written in other discussions). But you can still share your project on Github and I can have a look on your other bug as well.

**Comment by menez1111** [comment]
Hello. I do not set passive traffic systems just cars. Now I am sure intersections are the reason of the bug.When I set passive all of my intersections setting active and passive AI cars is working good.Using more than one system is also working fine. I think your system is nice and suitable to develop a game.  

I am sending the link of my project. Car_2 is the car which I added but this car doesnt stop when it is going to hit others some times others stop for not hitting this car you will see in the project. 

The last bug I found is whenever I set timescale to 0 ( for pause menu) and back to the time scale 1 all AI cars kind of jump and sometimes it cause to cars drop from the map or they kind of lost their connection with their agents. here is the video of it

https://www.youtube.com/watch?v=aM4JJML788U



Thanks for help. I hope you can solve them

**Comment by mchrbn** [comment]
Ah yes you are right, there is a bug with intersections when cars are set to active/passive. Will try to fix that.

**Comment by menez1111** [comment]
Thanks. Could you check the problem with the jumping car in the video. I think it is about timescale but I dont know the reason why they behave like this.

Also, If you need a logo or other simple visual element for the asset I can try to help, I am a design student.

**Comment by mchrbn** [comment]
I don't have this issue if I switch timescale from 0 to 1 or vice-versa. 

But anyway, this is more related to the engine than the traffic system, changing timescale affects the in-game physics. Check this [page](https://docs.unity3d.com/ScriptReference/Time-timeScale.html?_ga=2.220348440.1209994043.1600393805-1447745326.1580121990), you have to adjust Time.fixedDeltaTime also if you change the timeScale...Or maybe try to Lerp from one value to the other rather than just setting 0/1?

**Comment by mchrbn** [comment]
For the main issue of active/passive on intersections, try to replace Intersection.cs with this new script and let me know if it works!
[Intersection.zip](https://github.com/mchrbn/unity-traffic-simulation/files/5243156/Intersection.zip)

**Comment by menez1111** [comment]
It did not solve the problem.

The car causes the problem ( it happens when they are in intersection when switch of to passive)
![image](https://user-images.githubusercontent.com/53665690/93654181-e7073f80-fa24-11ea-99d9-1b6d082dd484.png)

Unchecking has to stop bool kind of help the car which stuck first but the next car in the order also stuck even you solve the problem with has to stop bool. Next car in the intersection start to move like 0.001 km so unchecking hastostopbool doesnt solve problem as I saw : https://youtu.be/t5gnrjxOwxY

**Comment by mchrbn** [comment]
Ok try to replace again these two files with the attached ones (Intersection and TrafficSystem).

Then **before** deactivating your cars, do `ts.SaveTrafficSystem();`
And **after** activating your cars, do `ts.ResumeTrafficSystem();`

For example (ts = the traffic system you are setting to active/passive):

```
ts.SaveTrafficSystem();
foreach(GameObject car in cars){
   car.SetActive(false);
 }
```

```
foreach(GameObject car in cars){
   car.SetActive(true);               
}
ts.ResumeTrafficSystem();
```


[ts.zip](https://github.com/mchrbn/unity-traffic-simulation/files/5251154/ts.zip)

**Comment by menez1111** [comment]
It looks like fixed ! Nice. I still have problem with setting a perfect traffic ( without accidents or traffic jam) but it really helped to performance thank you 👍 I only get this bug in the begining.

```
NullReferenceException: Object reference not set to an instance of an object
TrafficSimulation.Intersection.ResumeIntersectionStatus () (at Assets/unity-traffic-simulation-master/Assets/TrafficSimulation/Scripts/Intersection.cs:194)
TrafficSimulation.TrafficSystem.ResumeTrafficSystem () (at Assets/unity-traffic-simulation-master/Assets/TrafficSimulation/Scripts/TrafficSystem.cs:45)
PerformanceMapOne.OnTriggerEnter (UnityEngine.Collider collision) (at Assets/PerformanceMapOne.cs:36)

```

![image](https://user-images.githubusercontent.com/53665690/93724731-70984800-fbb2-11ea-992a-1f8cf65c5583.png)

**Comment by mchrbn** [comment]
Cool, glad it works!
For the error, I forgot to init the list, should be fixed now (you can replace your _Intersection.cs_ with the one from the git.
