### ISSUE TITLE
Mobile Performance

### ISSUE THREAD

**Issue by menez1111** [mchrbn/unity-traffic-simulation#18]
I am using traffic simulation happily on my project as you know. I use it for AI cars in my city. When there are 10 - 20 cars active my FPS drop to 600 to 300 ( on editor on computer 960m i5 6300hq) I am still trying to aim 60FPS for some 3 - 4 years old mobile phones ( now I get 30 - 40 but when I profile it the most expensive things AI car and AI car's physics ) but it is very hard with that. I know you are going to start to take a look on this asset when you are not bussy or if you want to. I wanted to list this issue if you can solve whenever you start to work on this asset again.

**Comment by mchrbn** [comment]
It took some time but you can check the new version. On my computer the scene went from 200FPS (old version) to 290FPS. However you will have to change few things to make it work with your current project as the vehicle's controller and "ai" are new.

**Comment by menez1111** [comment]
I will try the new version and I will give feedback to you. Thank you.
