### ISSUE TITLE
Slow Car Bug

### ISSUE THREAD

**Issue by menez1111** [mchrbn/unity-traffic-simulation#19]
Hello. It happens espically when you wait long time. A car starts to go slow and others have to wait for it. I dont know what is the reason of it maybe it can be intersections.

https://youtu.be/kkPRa0npxcs

**Comment by mchrbn** [comment]
Hey, I'm currently implementing a new CarAI that will be more performant as it won't use navmeshes (your #18 issue) and hopefully less buggy. Still have to improve/add few things but if I have time, I will try to push it to a new branch end of this week/next week. I will beep you when it is done so you can test it within your project

**Comment by menez1111** [comment]
Okay, thank you.

**Comment by mchrbn** [comment]
I rewrote the VehicleAI, check if this still happens!
