### ISSUE TITLE
Problems with new update

### ISSUE THREAD

**Issue by menez1111** [mchrbn/unity-traffic-simulation#20]
Hello, I tried the new update. When there is an accident one car goes back it is amazing  feature ! But I find a problem.

https://youtu.be/gnGZqEFc6OM
1. Cars dont follow the road ( they follow but with very wide angle) especially on the turns they just go out of the road. It causes to a lot of accident and cars get stuck because of it. I tested your example scene it also had the same problem. Traffic goes crazy in 2 minutes. If you remember I was using a lot of segments so cars were following the exact road. Also, it did not work in this update.

// small suggestions
2. I think downforce should be added to avoid turn over car.

3. I added wheel size option. May some people will need that small feature as well.

` public Vector3 whellsSize = new Vector3(1f, 1f, 1f);

        [Tooltip("Whether you want to animate the wheels")]
        public bool animateWheels = true;
        
        [Tooltip("The vehicle's drive type: rear-wheels drive, front-wheels drive or all-wheels drive.")]
        public DriveType driveType;

        private WheelCollider[] wheels;
        private float currentSteering = 0f;

        void OnEnable(){
            wheels = GetComponentsInChildren<WheelCollider>();

            for (int i = 0; i < wheels.Length; ++i) 
            {
                var wheel = wheels [i];

                // Create wheel shapes only when needed.
                if (leftWheelShape != null && wheel.transform.localPosition.x < 0)
                {
                    var ws = Instantiate (leftWheelShape);
                    ws.transform.parent = wheel.transform;
                    ws.transform.localScale = whellsSize;
                }
                else if(rightWheelShape != null && wheel.transform.localPosition.x > 0){
                    var ws = Instantiate(rightWheelShape);
                    ws.transform.parent = wheel.transform;
                    ws.transform.localScale = whellsSize;
                }`

**Comment by mchrbn** [comment]
Hey thanks for the feedbacks, for your issue, does it get better if you put a smaller value for the Waypoint Thresh? The smaller the value is, the more it should stick to the path. You can also try with a bigger steering angle value (so it turns faster).

Good suggestion for downforce, I will add it. For the wheel size, I'm not sure, maybe changing the radius value from the wheel collider is better than changing the scale?

**Comment by menez1111** [comment]
Hello.

Thank you for the advice.

It got better with your advice but still it did not work as much as the old system for me. I tried a lot of different things but I did not record them. I can share my project with you again if you want to test. May I made a mistake again. But I showed what is the problem for me also in your example scene. Still maybe it is not a problem for others but only for me.

This is a video about what is the problem.

https://youtu.be/r6a64Lky72k

And this video shows why I use a lot of segments :
 
https://youtu.be/pw7gx0YM9No

**Comment by mchrbn** [comment]
Yes would be good if you can share your project with me, so I can see how I can improve the system for various type of scene/roads!

**Comment by menez1111** [comment]
Thank you for the response  👍 

I showed my problems in the videos in the old message. The main problem for me is cars follow the waypoints with wide angle in the new update especially in the turns. I used to solve this  problem with having a lot of segments in the old version. Also, when aicars get hitted by the player car or the other ai car they were moving the closest segment with very narrow angle thanks to having a lot of segments. Achieving this with only using the waypoints would be perfect solution for me ( so we dont need to set hundreds of segments to achieve that).

**Comment by mchrbn** [comment]
Yes there is indeed an issue with the vehicle not following properly the path when it goes fast and there is sharp turns (unless it is an intersection like a stop or red light then the vehicle should slow down) . In my example, the max speed is pretty low that's why this issue is less visible. Will look at it and keep you updated

**Comment by mchrbn** [comment]
Check the branch dev, I've updated the scripts _WheelDrive.cs_ and _VehicleAI.cs_.
As you suggested, I added a value in _WheelDrive_ so you can set a downforce. The other thing that changed is that the vehicle will now reduce its speed before it is about to turn - you can set this value via _steeringSpeedMax_ in _WheelDrive_ (for example, if you set a value of 25, the vehicle's speed will be max 25KM/H when it is about to turn).

One thing that I noticed is that you should put a steering angle of at least 40 or even 50...30 is too small for sharp turns...Unless you create a curve with a lot of waypoints.

Do you think it improves your project?

Also look at these two videos: [01](https://drive.google.com/file/d/1Iu_CdkV4WyLclRmHNlYLvDCm_umKXkxd/view?usp=sharing) and [02](https://drive.google.com/file/d/1aRig97zkPRTuvxyXO3f1Pu-worx9lCO1/view?usp=sharing).

The first one is the result of these new scripts on your project; the second one is how I would create the traffic system for your project (as you mentioned, without that much segments. A segment should only be from one intersection to another).

**Comment by menez1111** [comment]
Hello again.



 I set up the new update. It looks like everything works fine. FPS increased significantly. I am not sure about the exact number but arround 250-260 to 310-330. I did not try it for very long hours but I can easily say number of cars getting stuck also droped. I will report if something new happens. 

 I will launch my game soon. Your project helped me a lot. Thank you so much. If you need my project to test the things or if you want to use my cars ( cars in the garage scene created by us) you are more than welcome. 

 I need only one thing more and I have a few suggestions if you want to develop the project more. It would be nice if AI cars can detect player's car so they avoid to hit the player as they do each other ( thats what I need). I checked some traffic systems in unity asset store.And my suggestions are : Mostly they have a respawn point and options about that. Also, some of them have their own occlusion culling system, most probably for increasing the performance. Idk why but in mobile or just in my game dynamic occlusion decreasing the performance may it can be helpfull for other platforms performance. Thats all what I was going to report. 

 

https://user-images.githubusercontent.com/53665690/103150988-cfa9c200-478a-11eb-9974-3df5b13f2c13.mp4

**Comment by mchrbn** [comment]
Cool glad to hear it is now working better :)

If you set the layer of your controlled car to "AutonomousVehicle" and have a BoxCollider on it, other cars should detect it no?

**Comment by menez1111** [comment]
Probably it can detect but i need to use another layer for player car because of a few reasons.

**Comment by mchrbn** [comment]
I updated the project, you can now add extra collision layers from the Traffic System GameObject - so you can add your main car's layer name and it will be also detected by the autonomous vehicles as an obstacle

**Comment by menez1111** [comment]
Hello. 
 I tried it. If I did not make a mistake there is a small problem. Cars hits to player's car once and after that they avoid to hit again. I think it is okay. Thank you.Happy new years.

**Comment by menez1111** [comment]
Hello again. I changed void onenable to void start because when you set pasive- active a car they instantiate wheels again.
