### ISSUE TITLE
Script errors in 5.6.7f1

### ISSUE THREAD

**Issue by KostyanSigaev** [mchrbn/unity-traffic-simulation#25]
When I open a project on Unity 5.6.7F1, I see CS4.0 errors, on this I installed SC6Supprot and get only two errors:
Assets\TraficSimulation\Scripts\Editor\TrafficEditor.cs(94,40) error CS1525: Invalid expression term 'float'
Assets\TraficSimulation\Scripts\Editor\TrafficEditor.cs(148,77) error CS1525: Invalid expression term 'bool'
Search for solutions on the Internet did not give results ... How to solve the problem?

P.S. I am not going to install newer editor versions, because it does not pull the computer and there is no support for DX9, which is very important to me

**Comment by mchrbn** [comment]
maybe declare the variable and then set it to the _out_

so instead of:
`plane.Raycast(ray, out float dst);`

```
float dst = 0f;
plane.Raycast(ray, out dst);
```

and same for the other one:
```
bool restructureSystem = false;
TrafficEditorInspector.DrawInspector(wps, out restructureSystem);
```
