### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by elhodel** [mchrbn/unity-traffic-simulation#3]
when i try to build the example i get the following error messages and the build fails:

```
Assets\TrafficSimulation\Scripts\TrafficSystem.cs(19,10): error CS0246: The type or namespace name 'MenuItemAttribute' could not be found (are you missing a using directive or an assembly reference?)

Assets\TrafficSimulation\Scripts\TrafficSystem.cs(19,10): error CS0246: The type or namespace name 'MenuItem' could not be found (are you missing a using directive or an assembly reference?)

Error building Player because scripts had compiler errors
```

**Comment by menez1111** [comment]
I canbuild my project. 
`[MenuItem("Component/Traffic` Simulation/Create Traffic Objects")]
        static void CreateTraffic(){
            GameObject mainGo = new GameObject("Traffic System");``

**Comment by mchrbn** [comment]
Yes there was some errors, I just pushed a version that should now work when you build.
