### ISSUE TITLE
Raycast Not working

### ISSUE THREAD

**Issue by TariqKhan-1** [mchrbn/unity-traffic-simulation#4]
cars are not detecting cars in front of it and not stopping or slowing down.
I can see rays when playing but it not working.

**Comment by yzq15** [comment]
Did you set the layers for the vehicles to be "AutonomousVehicle"

**Comment by mchrbn** [comment]
@TariqKhan-1 which Unity version are you using? Also are you trying from the demo scene provided or with your own setup level?

**Comment by mchrbn** [comment]
Just tested with Unity 2019.2.12, raycasts are working.
