### ISSUE TITLE
deleting waypoint gives continous error

### ISSUE THREAD

**Issue by Ashwin-097** [mchrbn/unity-traffic-simulation#5]
hi this is amazing code , but deleting way point gives continuous error till i delete traffic system , this makes it hard to make own traffic system , i hope u take a look in that 🥇 💯

**Comment by mchrbn** [comment]
hey @ashwinjxxx, when you delete a waypoint you have to click the "Re-Structure Traffic System" under the Traffic System gameobject to rebuild everything. Does that solve your problem?
